import type { Metadata } from "next";
import "./globals.css";
import 'i18n';
import { Plus_Jakarta_Sans } from "next/font/google";
import I18nProvider from "@/providers/I18nProvider";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
  icons: {
    icon: "/icon.png",
    shortcut: "/icon.png",
    apple: "/icon.png",
  },
};

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-jakarta",
  display: 'swap',
})


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={jakarta.variable}>
      <body style={{ fontFamily: 'var(--font-jakarta)' }}>
        <I18nProvider>
          {children}
          <ToastContainer />
        </I18nProvider>
      </body>
    </html>
  );
}
